---
deployment:
  tasks:
    # Use an ABSOLUTE path (or $HOME) so it's not created inside the repo
    - export DEPLOYPATH="$HOME/shout.stiwdio.com"

    # Ensure the target exists
    - /bin/mkdir -p "$DEPLOYPATH"

    # Copy repo -> live (rsync if available; otherwise cp -a)
    - /usr/bin/rsync -a --delete --exclude ".git" --exclude ".github" --exclude ".cpanel.yml" ./ "$DEPLOYPATH/" || /bin/cp -a ./ "$DEPLOYPATH/"

    # Leave a marker so you can verify in the browser
    - /bin/date > "$DEPLOYPATH/.deploy_log"